from datetime import date

from app.chat.field_spec import DocumentSpec, FieldSpec, party_fields

_PARTY_FIELDS = party_fields("provider", "customer", topic="Parties")

SPEC = DocumentSpec(
    key="software-license-agreement",
    catalog_names=("Software License Agreement",),
    catalog_filenames=("Software-License-Agreement.md",),
    catalog_description=(
        "Standard terms for licensing on-premises or self-hosted software, covering license "
        "grant, restrictions, updates, warranties, and liability."
    ),
    topics=(
        "Parties",
        "License and payment",
        "Warranty and support",
        "Liability and warranties",
        "Governing law and jurisdiction",
    ),
    party_role_labels={"provider": "Provider", "customer": "Customer"},
    fields=(
        FieldSpec(
            key="effectiveDate",
            label="Effective Date",
            topic="License and payment",
            type="date",
            order=0,
            required=False,
            default_factory=lambda: date.today().isoformat(),
            description="the date the Framework Terms start - state the default and ask the user to confirm or change it",
        ),
        FieldSpec(
            key="orderDate",
            label="Order Date",
            topic="License and payment",
            type="date",
            order=1,
            required=False,
            default_factory=lambda: date.today().isoformat(),
            description="the date this Order Form starts (often the same as the Effective Date) - state the default and ask the user to confirm or change it",
        ),
        FieldSpec(
            key="licensePeriod",
            label="Subscription Period",
            topic="License and payment",
            order=2,
            required=False,
            default="12 months",
            description="the length of the Subscription Period the Software is licensed for, e.g. '12 months' - state the default and ask the user to confirm or change it",
        ),
        FieldSpec(
            key="nonRenewalNoticeDate",
            label="Non-Renewal Notice Date",
            topic="License and payment",
            order=3,
            required=False,
            default="60 days before the end of the then-current Subscription Period",
            description="how much advance notice either party must give to prevent automatic renewal - state the default and ask the user to confirm or change it",
        ),
        FieldSpec(
            key="permittedUses",
            label="Permitted Uses",
            topic="License and payment",
            order=4,
            description="the business purposes Customer is licensed to use the Software for",
        ),
        FieldSpec(
            key="licenseLimits",
            label="License Limits",
            topic="License and payment",
            order=5,
            description="any limits on the license, e.g. number of users, servers, sites, or instances",
        ),
        FieldSpec(
            key="feesDescription",
            label="Fees",
            topic="License and payment",
            order=6,
            description="a description of the license Fees and any other charges, including amounts and what they cover (capture any fee schedule or line items as a single free-text description)",
        ),
        FieldSpec(
            key="paymentProcess",
            label="Payment Process",
            topic="License and payment",
            order=7,
            description="how and when Customer must pay Fees, e.g. invoicing terms, due dates, and whether payment is by invoice or automatic charge",
        ),
        FieldSpec(
            key="warrantyPeriod",
            label="Warranty Period",
            topic="Warranty and support",
            order=0,
            required=False,
            default="90 days from the Order Date",
            description="how long Provider warrants the Software will conform to the Documentation - state the default and ask the user to confirm or change it",
        ),
        FieldSpec(
            key="deletionProcedure",
            label="Deletion Procedure",
            topic="Warranty and support",
            order=1,
            description="the steps Customer must follow to uninstall and delete the Software upon termination or expiration",
        ),
        FieldSpec(
            key="additionalWarranties",
            label="Additional Warranties",
            topic="Warranty and support",
            order=2,
            required=False,
            default="None",
            description="any additional warranties either party makes beyond the standard mutual warranties - state the default of 'None' and ask the user to confirm or change it",
        ),
        FieldSpec(
            key="generalCapAmount",
            label="General Cap Amount",
            topic="Liability and warranties",
            order=0,
            description="the default cap on each party's total liability for ordinary claims, e.g. 'the Fees paid in the 12 months before the claim'",
        ),
        FieldSpec(
            key="increasedClaims",
            label="Increased Claims",
            topic="Liability and warranties",
            order=1,
            required=False,
            default="None",
            description="claim types (if any) subject to a higher liability cap than the General Cap Amount, e.g. confidentiality breaches - state the default of 'None' and ask the user to confirm or change it",
        ),
        FieldSpec(
            key="increasedCapAmount",
            label="Increased Cap Amount",
            topic="Liability and warranties",
            order=2,
            required=False,
            default="Not applicable",
            description="the higher liability cap that applies to Increased Claims, if any - state the default and ask the user to confirm or change it",
        ),
        FieldSpec(
            key="unlimitedClaims",
            label="Unlimited Claims",
            topic="Liability and warranties",
            order=3,
            required=False,
            default="None",
            description="claim types (if any) with no liability cap at all, e.g. gross negligence or willful misconduct - state the default of 'None' and ask the user to confirm or change it",
        ),
        FieldSpec(
            key="providerCoveredClaims",
            label="Provider Covered Claims",
            topic="Liability and warranties",
            order=4,
            description="the third-party claims Provider agrees to indemnify Customer against, e.g. claims that the Software infringes a third party's intellectual property rights",
        ),
        FieldSpec(
            key="customerCoveredClaims",
            label="Customer Covered Claims",
            topic="Liability and warranties",
            order=5,
            description="the third-party claims Customer agrees to indemnify Provider against, e.g. claims arising from Customer's misuse of the Product",
        ),
        FieldSpec(
            key="governingLaw",
            label="Governing Law",
            topic="Governing law and jurisdiction",
            order=0,
            description="a state or country whose law governs the agreement",
        ),
        FieldSpec(
            key="chosenCourts",
            label="Chosen Courts",
            topic="Governing law and jurisdiction",
            order=1,
            description="the courts where the parties must bring legal disputes about the agreement",
        ),
        *_PARTY_FIELDS,
    ),
)
